import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const {Workbook,SpreadsheetFile}=await import(pathToFileURL(path.join(process.env.MARKET_NODE_MODULES,'@oai/artifact-tool/dist/artifact_tool.mjs')).href);
const out=path.resolve(process.argv[2]),p=JSON.parse(await fs.readFile(path.join(out,'table-validation-plan.json'),'utf8'));
const wb=Workbook.create(),s=wb.worksheets.add(p.input_sheet),n=p.details.length+3;
s.getRange('A1:R1').merge();s.getRange('A1').values=[[`${p.as_of} ${p.banks.join(' / ')} 挂牌明细`]];
s.getRange('A2:R2').merge();s.getRange('A2').values=[['本页为报价输入。按用户规则，利率数字统一按百分数使用；不要求原文出现p.a.。I列为可插表数值，J列保留原始数字。原CNH按用户规则在调研和彩虹表中使用CNY，明细保留CNH；不采集JPY。']];
s.getRange('A3:R3').values=[['银行','币种','类别','产品','实际期限','客群 / 渠道','金额下限','金额上限','利率','原始数值 / 单位','金额币种','生效日','采集日','核验状态','条件','来源','金额边界','银行标注日期']];
const run=JSON.parse(await fs.readFile(path.join(p.source_run,'run.json'),'utf8')),pages=Object.fromEntries(run.pages.map(x=>[x.id,x]));
s.getRange(`A4:R${n}`).values=p.details.map(r=>[r.bank,r.currency,'挂牌',r.product_name,`${r.tenor_value}${r.tenor_unit}`,r.audience+' / '+r.channel,r.amount_min===null?'未列明':Number(r.amount_min),r.amount_max===null?'未列明':Number(r.amount_max),r.insertable?Number(r.rate_pct)/100:'-',r.rate_pct+'%',r.amount_currency+(r.amount_is_equivalent?'等值':''),r.valid_from||'未列明',r.evidence_date||p.as_of,r.manual_reviewed?'用户已确认':r.insertable?'自动核验通过，已插表':r.hold_reason||'暂不插表，见条件',r.conditions,[...new Set(r.evidence.map(e=>pages[e.page_id]?.url).filter(Boolean))].join('\n'),`${r.min_inclusive?'含':'不含'}下限；${r.max_inclusive?'含':'不含'}上限`,r.source_date||'未列明']);
s.getRange(`A1:R${n}`).format={font:{name:'Microsoft YaHei',size:10},wrapText:true,verticalAlignment:'center',rowHeight:48};
s.getRange('A1:R1').format={fill:'#173D54',font:{color:'#FFFFFF',bold:true,size:14},rowHeight:32};
s.getRange('A2:R2').format.rowHeight=42;s.getRange('A3:R3').format={fill:'#DDEBF7',font:{bold:true}};
s.getRange(`A3:R${n}`).format.borders={preset:'all',style:'thin',color:'#C9D5DD'};
for(const [c,w] of Object.entries({A:9,B:9,C:9,D:28,E:11,F:23,G:16,H:17,I:16,J:23,K:13,L:15,M:15,N:35,O:50,P:70,Q:22,R:17}))s.getRange(`${c}1:${c}${n}`).format.columnWidth=w;
s.getRange(`G4:H${n}`).setNumberFormat('#,##0.##');s.getRange(`I4:I${n}`).setNumberFormat('0.0000%');s.getRange(`N4:N${n}`).format.fill='#FFF2CC';s.showGridLines=false;
wb.recalculate();await(await SpreadsheetFile.exportXlsx(wb)).save(path.join(out,'board-inputs.xlsx'));
console.log('Board input rows:',p.details.length);
